import{_ as n}from"./plugin-vue_export-helper-DlAUqK2U.js";import{c as i,b as a,o as s}from"./app-ptbqs2O5.js";const t={};function l(r,e){return s(),i("div",null,e[0]||(e[0]=[a(`<p>在程序出现一些错误时，一般会抛出错误，并结束程序。</p><h2 id="异常的概念" tabindex="-1"><a class="header-anchor" href="#异常的概念"><span>异常的概念</span></a></h2><p>异常指在程序出现问题时抛出的内容，而程序出现错误时终止程序并显示错误信息的过程叫做抛出异常。</p><p>抛出异常可以有效防止程序出现预期以外的结果，并防止一错再错。</p><h2 id="异常的常见类型" tabindex="-1"><a class="header-anchor" href="#异常的常见类型"><span>异常的常见类型</span></a></h2><p><code>NameError</code>：常见于与名称相关的内容，比如未定义变量/函数就使用，就像这样：</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34;"><pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>Traceback (most recent call last):</span></span>
<span class="line"><span>  File &quot;&lt;python-input-1&gt;&quot;, line 1, in &lt;module&gt;</span></span>
<span class="line"><span>    value</span></span>
<span class="line"><span>NameError: name &#39;value&#39; is not defined</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code>ValueError</code>：常见于函数收到的参数类型合法，但是内容不合法（比如向<code>int()</code>函数内传入包含非十进制数的字符串），就像这样：</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34;"><pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>Traceback (most recent call last):</span></span>
<span class="line"><span>  File &quot;&lt;python-input-4&gt;&quot;, line 1, in &lt;module&gt;</span></span>
<span class="line"><span>    int(value)</span></span>
<span class="line"><span>    ~~~^^^^^^^</span></span>
<span class="line"><span>ValueError: invalid literal for int() with base 10: &#39;1234a&#39;</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code>SyntaxError</code>：常见于程序出现其它语法错误（比如变量名不合法），就像这样：</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34;"><pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>Traceback (most recent call last):</span></span>
<span class="line"><span>  File &quot;&lt;python-input-6&gt;&quot;, line 1</span></span>
<span class="line"><span>    if = 0</span></span>
<span class="line"><span>       ^</span></span>
<span class="line"><span>SyntaxError: invalid syntax</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code>if</code>作为Python的关键字之一，不允许被用作变量名，因此程序抛出<code>SyntaxError</code>。</p><p><code>TypeError</code>：常见于程序尝试执行的操作不支持特定类型的参数（比如试图比较数字和字符串），就像这样：</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34;"><pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>Traceback (most recent call last):</span></span>
<span class="line"><span>  File &quot;&lt;python-input-8&gt;&quot;, line 1, in &lt;module&gt;</span></span>
<span class="line"><span>    0 &lt; &quot;func&quot;</span></span>
<span class="line"><span>TypeError: &#39;&lt;&#39; not supported between instances of &#39;int&#39; and &#39;str&#39;</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code>ZeroDivisionError</code>：常见于程序试图将某数字除以0，就像这样：</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34;"><pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>Traceback (most recent call last):</span></span>
<span class="line"><span>  File &quot;&lt;python-input-10&gt;&quot;, line 1, in &lt;module&gt;</span></span>
<span class="line"><span>    123/0</span></span>
<span class="line"><span>    ~~~^~</span></span>
<span class="line"><span>ZeroDivisionError: division by zero</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div>`,16)]))}const c=n(t,[["render",l],["__file","exception-concept-type.html.vue"]]),d=JSON.parse('{"path":"/docs/python-exception-handling/exception-concept-type.html","title":"异常的概念与常见类型","lang":"zh-CN","frontmatter":{"title":"异常的概念与常见类型","tag":"Python, 异常处理：让程序更稳健, 异常的概念与常见类型","author":"灵魂歌手er","description":"在程序出现一些错误时，一般会抛出错误，并结束程序。 异常的概念 异常指在程序出现问题时抛出的内容，而程序出现错误时终止程序并显示错误信息的过程叫做抛出异常。 抛出异常可以有效防止程序出现预期以外的结果，并防止一错再错。 异常的常见类型 NameError：常见于与名称相关的内容，比如未定义变量/函数就使用，就像这样： ValueError：常见于函数收...","head":[["meta",{"property":"og:url","content":"https://py.hello8693.xyz/docs/python-exception-handling/exception-concept-type.html"}],["meta",{"property":"og:site_name","content":"Python 教程"}],["meta",{"property":"og:title","content":"异常的概念与常见类型"}],["meta",{"property":"og:description","content":"在程序出现一些错误时，一般会抛出错误，并结束程序。 异常的概念 异常指在程序出现问题时抛出的内容，而程序出现错误时终止程序并显示错误信息的过程叫做抛出异常。 抛出异常可以有效防止程序出现预期以外的结果，并防止一错再错。 异常的常见类型 NameError：常见于与名称相关的内容，比如未定义变量/函数就使用，就像这样： ValueError：常见于函数收..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2024-12-29T00:40:29.000Z"}],["meta",{"property":"article:author","content":"灵魂歌手er"}],["meta",{"property":"article:tag","content":"Python, 异常处理：让程序更稳健, 异常的概念与常见类型"}],["meta",{"property":"article:modified_time","content":"2024-12-29T00:40:29.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"异常的概念与常见类型\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2024-12-29T00:40:29.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"灵魂歌手er\\"}]}"]]},"headers":[{"level":2,"title":"异常的概念","slug":"异常的概念","link":"#异常的概念","children":[]},{"level":2,"title":"异常的常见类型","slug":"异常的常见类型","link":"#异常的常见类型","children":[]}],"git":{"createdTime":1734756596000,"updatedTime":1735432829000,"contributors":[{"name":"LHGS-github","username":"LHGS-github","email":"340994706@qq.com","commits":1,"url":"https://github.com/LHGS-github"},{"name":"hello8693","username":"hello8693","email":"1320998105@qq.com","commits":1,"url":"https://github.com/hello8693"}]},"readingTime":{"minutes":1.44,"words":432},"filePathRelative":"docs/python-exception-handling/exception-concept-type.md","localizedDate":"2024年12月21日","autoDesc":true}');export{c as comp,d as data};
